add_newline = false

format = """
$custom\
$all\
$kubernetes\
$fill \
$time\
$line_break\
$character
"""

[fill]
symbol = " "

[username]
style_user = "213 bold"
style_root = "bright-red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[line_break]
disabled = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold bright-red)"
vicmd_symbol = "[N](bold green) "

[directory]
read_only = " ï ½"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "99 bold"

[kubernetes]
disabled = false
style = "213 bold"
format = 'on [â›µ $symbol$context( \($namespace\))]($style) '

[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:.*:cluster/staging" = "staging"
"arn:aws:eks:eu-central-1:.*:cluster/tatooine" = "tatooine"
"arn:aws:eks:eu-central-1:.*:cluster/production" = "production"


[time]
disabled = false
use_12hr = false
format = '[ $time ]($style) '
time_format = "%T"
utc_time_offset = "local"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
# symbol = "â˜ï¸ "
symbol = "ğŸŒ¨ï¸  "

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸš€"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = " ğŸ¦„ "
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

